name: android13_app_protection_remove

on:
  workflow_dispatch:
    inputs:
     ROM_URL:
      description: 'Services.jar Url'
      required: true
      default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Setup JAVA
         uses: actions/setup-java@v4
         with:
          java-version: '8'
          distribution: 'microsoft'
  
       - name: Setting up
         run: |
            sudo apt-get install -y git default-jre wget zip unzip aapt axel python3-pip zipalign apksigner xmlstarlet libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev libzstd-dev attr ccache clang golang libbrotli-dev 
            pip3 install ConfigObj
  
       - name: Set up Time 
         run: |
            cd $GITHUB_WORKSPACE
            echo "Setting Vienam timezone"
            sudo timedatectl set-timezone Asia/Ho_Chi_Minh
      
       - name: Download Services.jar
         run: |
            axel -n $(nproc) ${{ github.event.inputs.ROM_URL }}
            
       - name : PATCH-ING
         run: |
            sudo chmod 777 -R *
            sudo bash fvckximi.sh
       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v3.1.1
         with:
          # Artifact name
           name: services_patched.zip
          # A file, directory or wildcard pattern that describes what to upload
           path: ./module/*
          # The desired behavior if no files are found using the provided path.
      
