name: ttt

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Services.jar Url'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
       

      - name: Setting up
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget zip unzip axel python3-pip zipalign apksigner xmlstarlet
          pip3 install ConfigObj

      - name: Set up Time
        run: |
          echo "Setting Vietnam timezone"
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh

      - name: Download Services.jar
        run: |
          axel -n $(nproc) ${{ github.event.inputs.ROM_URL }}

      - name: PATCH-ING
        run: |
          sudo chmod 777 -R *
          ./test.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: services_patched.zip
          path: ./module/*
          if-no-files-found: error
